import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,100&display=swap" rel="stylesheet" />

      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/weather" as="/weather">
            Weather
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
